# iata_codes.py

city_to_iata = {
    "stockholm": "STO",
    "tokyo": "TYO",
    "paris": "PAR",
    "berlin": "BER",
    "madrid": "MAD",
    "new york": "NYC",
    "london": "LON",
    "rome": "ROM",
    "bangkok": "BKK",
    "dubai": "DXB",
    "antalya": "AYT",
    "barcelona": "BCN",
    "copenhagen": "CPH",
    "dublin": "DUB",
    "edinburgh": "EDI",
    "helsinki": "HEL",
    "istanbul": "IST",
    "lisbon": "LIS",
    "milan": "MIL",
    "oslo": "OSL",
    "prague": "PRG",
    "venice": "VCE",
    "zurich": "ZRH",
    "amsterdam": "AMS",
    "athens": "ATH",
    "budapest": "BUD",
    "brussels": "BRU",
    "vienna": "VIE",
    "warsaw": "WAW",
    "zagreb": "ZAG",
    "tehran": "IKA",
    "beijing": "PEK",
    "tabiriz": "TBZ",
    "paris": "CDG",
    "manchester": "MAN",

        # Add more as needed
}